name=TekuteruServo
version=1.0.0
author=tekuteru
maintainer=tekuteru <tekuteruteku@gmail.com>
sentence=Arduino Library for controlling TekuteruServo
paragraph=A high-performance serial servo library featuring multi-turn positioning, real-time feedback, and adjustable speed control.
category=Device Control
url=https://github.com/tekuteru/TekuteruServo-Arduino
architectures=*
license=Apache-2.0